name: Generate Snake Game

on:
  schedule:
    - cron: "0 */12 * * *"  # Every 12 hours
  workflow_dispatch:

jobs:
  build:
    name: Generate SVG Snake Animation
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Harshavardhanjakku
          outputs: |
            dist/github-contribution-grid-snake.svg
          snake_color: '#1E90FF'  # Optional: Customize color as hex or name

      - name: Deploy SVG to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
